name: new31
version: 20130522

libraries:
- name: "django"
  version: "1.5"

handlers:
- url: /static
  static_dir: static
  static_path: static

- url: /robots.txt
  static_path: robots.txt

- url: /favicon.ico
  static_path: favicon.ico

- url: /static/
  gzip: on

- url: /a-big-file.txt
  gzip: on